version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - tah-postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  tah-postgres-volume:
